def home_screen_menu():
    print (24 * "-" , "COVID-19 Project" , 24 * "-")
    print ("Group 23")
    print ("By: Matthew Tang, Selina Ali, Naziba Haider")

def print_menu():
    print (30 * "-" , "MENU" , 30 * "-")
    print ("1. Confirmed COVID-19 Cases")
    print ("2. Deaths")
    print ("3. Recovered")
    print ("4. Transmission")
    print ("5. COVID-19 Testing")
    print ("6. Exit")
    print (67 * "-")

def general_information_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose a Filter")
    print ("1. Region")
    print ("2. Timeline")
    print ("3. Gender")
    print ("4. Age Group")
    print ("5. Occupation")
    print ("6. More than 1 Filter")
    print ("7. Go Back")
    print (67 * "-")

def region_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose a Region")
    print ("1. Atlantic (New Brunswick, Nova Scotia, Prince Edward Island, Newfoundland and Labrador)")
    print ("2. Quebec")
    print ("3. Ontario and Nunavut")
    print ("4. Prairies (Alberta, Saskatchewan, Manitoba, Northwest Territories)")
    print ("5. Northwest Territories (British Columbia, Yukon)")
    print ("6. Go Back")
    print (67 * "-")

def timeline_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose a Timeline")
    print ("1. Week 36 (Week of September 6th)")
    print ("2. Week 37 (Week of September 13th)")
    print ("3. Week 38 (Week of September 20th)")
    print ("4. Week 39 (Week of September 27th)")
    print ("5. Week 40 (Week of October 4th)")
    print ("6. Week 41 (Week of October 11th)")
    print ("7. Week 42 (Week of October 18th)")
    print ("8. Week 43 (Week of October 25th)")
    print ("9. Go Back")
    print (67 * "-")

def gender_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose a Gender")
    print ("1. Male")
    print ("2. Female")
    print ("3. Not Stated/Other")
    print ("4. Go Back")
    print (67 * "-")

def ageGroup_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose an Age Group")
    print ("1. 0-19")
    print ("2. 20-29")
    print ("3. 30-29")
    print ("4. 40-49")
    print ("5. 50-59")
    print ("6. 60-69")
    print ("7. 70-79")
    print ("8. 80+")
    print ("9. Go Back")
    print (67 * "-")

def occupation_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose an Occupation")
    print ("1. Health Care Workers")
    print ("2. School or daycare workers")
    print ("3. Long term care residents")
    print ("4. Other")
    print ("5. Not Stated")
    print ("6. Go Back")
    print (67 * "-")

def weekly_testing_menu():      
    print (30 * "-" , "MENU" , 30 * "-")
    print ("Choose a Filter")
    print ("1. Region")
    print ("2. Timeline")
    print ("3. Region and Timeline")
    print ("4. Go Back")
    print (67 * "-")